[project]
name = "pdf-to-audiobook"
version = "0.1.0"
description = "Convert PDF books into high-quality audiobooks using Kokoro TTS"
readme = "README.md"
dependencies = [
    "torch",
    "torchvision",
    "pymupdf>=1.25.0",
    "soundfile>=0.13.0",
    "numpy>=1.26.0",
    "regex>=2024.0.0",
    "num2words>=0.5.14",
    "beautifulsoup4>=4.13.0",
    "lxml>=5.3.0",
    "kokoro>=0.9.0",
    "piper",
    "qwen-tts"
]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/nightly/rocm7.2"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-rocm" }
torchvision = { index = "pytorch-rocm" }
pytorch-triton-rocm = { index = "pytorch-rocm" }
triton-rocm = { index = "pytorch-rocm" }



[project.scripts]
pdf-to-audiobook = "cli:main"

[tool.taskipy.tasks]
nougat = "uvx --python 3.11   --with 'transformers<4.36.0'   --with 'albumentations<1.4.0' --with 'pypdfium2>=4.0.0,<4.25.0'  --extra-index-url https://download.pytorch.org/whl/rocm7.2   --from nougat-ocr nougat pdfs/book.pdf -o mmd"
make_wavs = "uv run python -m make_wavs"